apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestore-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestore-server
  template:
    metadata:
      labels:
        app: filestore-server
    spec:
      containers:
      - name: go-http-server
        image: ayushsatyam146/filestore-server  
        ports:
        - containerPort: 8080     