apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-http-server
  template:
    metadata:
      labels:
        app: go-http-server
    spec:
      containers:
      - name: go-http-server
        image: filestore-server   # Replace with your actual Docker image
        ports:
        - containerPort: 8080      # Replace with the port your Go HTTP server listens on
