apiVersion: v1
kind: Service
metadata:
  name: go-http-service
spec:
  selector:
    app: go-http-server
  ports:
  - protocol: TCP
    port: 8080              # Replace with the desired external port
    targetPort: 8080     # Replace with the port your Go HTTP server listens on
  type: LoadBalancer    # Use "NodePort" or "ClusterIP" if running on a local Kubernetes cluster
